services:
  app:
    image: maven:3.9.9-eclipse-temurin-21-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trabalho
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
    command: mvn spring-boot:run

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: trabalho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
